### PR TITLE
Add resources list

### PR DESCRIPTION
**Pull request by petergoes**
## Summary

Proposed changes:
- Add `More Resources` section
## Checklist
- [X] The changes only affect or contain one style guide rule or section.
- [X] The new style guide section has an entry in the [Table of Contents](/README.md#table-of-contents) (only if changes introduce new section).
- [X] The changes can be merged into the target branch without conflicts.

### CODE REVIEW

**Comment by jbmoelker** [comment]
what I find difficult about this section is that it suggests "further reading", while really our guide is more like an addendum to the original docs (guide + api) on riotjs.com. And the egghead videos are really an introduction as well. So I'm not sure about the relation between the "more resources" and our guide.

**Comment by phortuin** [comment]
Agree with Jasper, the riotjs api/guide docs are a given if anyone wants to know more about Riot. Egghead is not a fully free service, so reluctant to link there. Also, since this is a style guide and not a 'how to Riot', I think those videos are besides the point. "Further reading" _could_ point towards our (future) docs for writing good README's or other more generic style guides. But that's not for now

**Comment by petergoes** [comment]
I get your points, so remove this whole section and wait for a more appropriate time/formulation?

**Comment by jbmoelker** [comment]
@petergoes yes I agree, keep it out for now. I'd say close this branch & PR and #21 as well until we have more to show for it.

**Pull request closed without merging**
