### PR TITLE
added [data-is=...] rules for css scoping

### PR DESCRIPTION
**Pull request by moritzschepp**
## Summary

Proposed changes:
- adding css scopes for <... data-is="my-example"></...> mounting

### CODE REVIEW

**Comment by jbmoelker** [comment]
@moritzschepp thank you for creating this PR.

I can imagine adding this to the guidelines. However I think the current changes to the README obfuscate the most common use case, which is a custom element. So instead I'd rather add it as a note to that section:

> note: If you're using [`data-is=`](http://riotjs.com/guide/#html-elements-as-tags) (introduced in [v2.3.17](http://riotjs.com/release-notes/#march-9-2016)) to initiate Riot tags, you can use `[data-is="my-example"]` as CSS selector instead of `.my-example`.

@moritzschepp do you agree?

**Comment by moritzschepp** [comment]
@jbmoelker sure, that'd certainly be enough. Le me see how changing a PR actually works ...

**Comment by moritzschepp** [comment]
... so I think this should be changed now.

**Comment by jbmoelker** [comment]
@moritzschepp Thanks! And sorry for being picky, but I'd also like `data-is=` and `v2.3.17` to be links so that people not familiair with it can find it in the docs, and know whether they can use it with their Riot version.

``` markdown
note: If you're using [`data-is=`](http://riotjs.com/guide/#html-elements-as-tags) (introduced in [v2.3.17](http://riotjs.com/release-notes/#march-9-2016)) to initiate Riot tags, you can use `[data-is="my-example"]` as CSS selector instead of `.my-example`.
```

**Comment by moritzschepp** [comment]
Of course, please be picky! I'll push that shortly.

**Comment by jbmoelker** [comment]
Thank you!

**Pull request merged**
