### PR TITLE
Module based development

### PR DESCRIPTION
**Pull request by jbmoelker**

### CODE REVIEW

**Comment by petergoes** [comment]
Lets start out with a ToC and implementing the contribution rules right away by adding a **why** and maybe a short **how** section

Suggestion:

``` markdown
### Why?
> Smaller APIs are easier to learn and teach to others. This is generally helped if you [do one thing and do it well](http://en.wikipedia.org/wiki/Single_responsibility_principle).
> - Addy Osmani

### How?
Make sure your module does only one thing. Develop it in it's own environment (preferably on a dedicated demo page).
```

**Comment by petergoes** [comment]
I think this covers the topic. But maybe it is a bit light? Should we explain a bit more what a module is? Now the explanation is all the way down in the How? section (From the How? section we learn that a module is Focused, Independent, Reusable, Small and Testable)

**Comment by jbmoelker** [comment]
Link to (Modularity in RiotJS](http://riotjs.com/guide/application-design/#modularity)?

**Comment by jbmoelker** [comment]
@petergoes in response to 1#issuecomment-186122487 I've rewritten the summary to relate it to Riot tags and the why to explain how to recognise when to split modules.

**Comment by petergoes** [comment]
I think this is a better way of formulating it. Can be merged if it's up to me!

**Pull request merged**
