### PR TITLE
"use `<script>` inside tag" rule

### PR DESCRIPTION
**Pull request by jbmoelker**
## Summary

Proposed changes:
- always use `<script>` inside tag.
## Checklist
- [X] The changes only affect or contain one style guide rule or section.
- [X] The changes are in [style guide format](/CONTRIBUTING.md#format).
- [X] The new style guide section has an entry in the [Table of Contents](/README.md#table-of-contents) (only if changes introduce new section).
- [X] The changes can be merged into the target branch without conflicts.

### CODE REVIEW

**Comment by petergoes** [comment]
the examples (recommended / avoid sections) are markup, not javascript. So the comments should be converted to `<!--` and `-->` as well.
/nitpick mode off

Good section, ready when up to me

**Comment by jbmoelker** [comment]
you're totally right! fixed.

**Comment by jbmoelker** [comment]
closed by 8050cff

**Comment by jbmoelker** [comment]
closed by 8050cff

**Pull request closed without merging**
